Added EKS description and VPC deletion
k0rdent/olddocs pull request #13
Opened 2024-10-16 17:07 UTC by slysunkin

# Description

Added EKS description and manual VPC deletion procedure.

2024-10-16 20:00 UTC, squizzi submitted a review, later dismissed

2024-10-16 20:00 UTC, squizzi commented on docs/eks/main.md
> +2. `AWS`: Ensure you have the AWS CLI installed and configured with the necessary IAM permissions.
I think you should link to the AWS CLI page here:

```suggestion
2. `AWS`: Ensure you have the [AWS CLI installed](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and configured with the necessary IAM permissions.
```

What necessary IAM provisions are required?  What type of scope is needed to deploy on EKS?  List them here.

2024-10-16 20:00 UTC, squizzi commented on docs/eks/main.md
> +Follow the AWS IAM [setup quide](../aws/cloudformation.md#aws-iam-setup).
Is this a prereq?  It seems similar to the `with the necessary IAM provisions` section above.

2024-10-16 20:00 UTC, squizzi commented on docs/eks/main.md
> +## EKS clsuter creation
```suggestion
## EKS cluster creation
```

2024-10-16 20:00 UTC, squizzi commented on docs/eks/main.md
> +`export DEV_PROVIDER=eks` variable are essential for EKS cluster creation with Project 2A
This env var is a development specific thing to help developers deploy EKS clusters, it's probably a better fit for documentation that lives in the project2a product.  This documentation should be targetted at end users.  How would someone create a `ManagedCluster` without the `Makefile` targets we use in dev?  An example `ManagedCluster` with `kubectl apply` of that would be a better fit here.

2024-10-16 20:00 UTC, squizzi commented on docs/eks/main.md
> +After the creation process completes, verify that your EKS cluster is running:
After the creation process completes.. but how do I monitor the creation process?  What happens if I never reach `ACTIVE`?  Perhaps talk about using `clusterctl` or add specific general section to the docs about using the `clusterctl` binary to inspect clusters no matter the provider.

2024-10-16 20:00 UTC, squizzi commented on docs/eks/main.md
> +## Update kubeconfig
Is this necessary?  Do we even need to list `eksctl` as a prereq?  `eksctl get cluster` is satisfied by the `clusterctl` binary which can be used to check deployment status and the `update-kubeconfig` command while useful is satisfied already by just loading the `kubeconfig` from secret like we do for our other providers.  I think generalizing all of this for all providers and adding a verifying and accessing the cluster section and linking to that here is a better choice.

2024-10-16 20:00 UTC, squizzi commented on docs/eks/vpc-removal.md
> +# Manual removal of VPCs
Why is this needed?  Explain why manual removal of VPCs may be necessary, what types of situations would someone encounter that would lead to this?  An example of maybe some `clusterctl` output where deletion of the VPCs is failing would be useful here so users know what to look for before they try to conduct deletions themselves.

2024-10-17 17:13 UTC, a13x5 requested changes
Several notes:
1. EKS is a part of AWS, so it should be in the AWS section (as a separate paragraph)
2. We still haven't created the bug in the upstream which we can refer to in the workaround. IMO workaround makes zero sense without a bug (in the CAPA upstream, since it's not our functionality)

2024-10-17 20:59 UTC, slysunkin commented
> Several notes:
> 
> 1. EKS is a part of AWS, so it should be in the AWS section (as a separate paragraph)
> 2. We still haven't created the bug in the upstream which we can refer to in the workaround. IMO workaround makes zero sense without a bug (in the CAPA upstream, since it's not our functionality)

I created this bug report last week: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5150

2024-10-18 01:04 UTC, a13x5 commented
> I created this bug report last week: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5150
Cool! I missed it somehow. Let's then mention it explicitly, something like "here we have a bug in CAPA and to mitigate this issue do the following"
It's will be much better

2024-10-31 03:16 UTC, Schnitzel commented
this is broken because of https://github.com/Mirantis/project-2a-docs/pull/25 I will fix this

2024-11-04 22:32 UTC, slysunkin commented
> this is broken because of #25 I will fix this

I reworked my PR, now it has no conflicts.

2024-11-06 02:27 UTC, Schnitzel requested changes

2024-11-06 02:27 UTC, Schnitzel commented on docs/eks/main.md
> +3. `eksctl`: Install eksctl by following the official guide. This utility is required for troubleshooting EKS clusters.
why do we need `eksctl`? I don't see it used anywhere?

2024-11-06 02:27 UTC, Schnitzel commented on docs/quick-start/aws.md
> +
can we add this under ClusterTemplates > AWS > EKS instead of in the quickstart guide? the quickstart should really be to do a quick start and creating an EKS cluster is unfortunately not fast ;), so we're using a hosted CP in the quickstarts.

2024-11-06 04:18 UTC, slysunkin commented on docs/eks/main.md
> +3. `eksctl`: Install eksctl by following the official guide. This utility is required for troubleshooting EKS clusters.
removed

2024-11-06 04:19 UTC, slysunkin commented on docs/quick-start/aws.md
> +
Moved to ClusterTemplates and reworked

2024-11-06 15:35 UTC, a13x5 requested changes
EKS is a part of AWS, so it should be in the AWS section (as a separate paragraph). I will insist on that, since it makes no sense to have the whole separate section for EKS (with the same AWS parameters)

2024-11-06 15:35 UTC, a13x5 commented on docs/clustertemplates/eks/vpc-removal.md
> +GuardDuty creates an extra VPCE (VPC Endpoint) not managed by CAPA and when CAPA starts EKS cluster removal, this VPCE is not removed.
We should add this explanation on the top, since this is a root cause.

2024-11-12 00:06 UTC, a13x5 requested changes
Please add the EKS related info in the AWS docs (`docs/clustertemplates/aws/template-parameters.md`). No need to create the separate EKS sections, since it's a part of AWS.

The images should be located in `docs/assets` with all other images.

2024-11-15 19:50 UTC, slysunkin commented
:bell: can I have a review, please?

2024-11-15 19:59 UTC, Schnitzel approved these changes

2024-11-15 19:59 UTC, merged

2024-11-15 20:00 UTC, Schnitzel commented
sorry! approved and merged :)