hmc-351: add dockerfile for local dev
k0rdent/olddocs pull request #2
Opened 2024-09-24 17:06 UTC by PrashantR30

This PR resolves https://github.com/Mirantis/hmc/issues/351 by adding Dockerfile to allow local update of the docs code base.

2024-09-24 22:03 UTC, a13x5 requested changes
Mostly remarks on Makefile. Instruction must be simplified, since there is no need for so much steps - all can be easily automated.

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +run:
Add dependency on `build`

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +all: build run
Just leave the `run` target with dependency

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +	docker run --rm -p $(PORT):8000 -v $(shell pwd):/docs --name $(CONTAINER_NAME) $(DOCKER_IMAGE):$(DOCKER_TAG)
Just use `$(PWD)`, no need to call `pwd` shell command here

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +stop:
Should also call `docker rm`

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +clean:
Dependency on stop - you can't delete image which is in use

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +	docker stop $(CONTAINER_NAME) || true
Non zero exit shouldn't be masked. Remove `|| true`

2024-09-24 22:03 UTC, a13x5 commented on Makefile
> +	docker rmi $(DOCKER_IMAGE):$(DOCKER_TAG) || true
Remove `|| true`

2024-09-24 22:03 UTC, a13x5 commented on docker/Dockerfile
> +COPY requirements.txt .
Remove. Just use `COPY . .` here once.
In addition to that the `requirements.txt` is added into `docker` directory - this isn't reflected here.

2024-09-24 22:03 UTC, a13x5 commented on docker/README.md
> +### 4. Full Workflow Example
Simplify this. With proper changes user will only need to run `make`

2024-09-24 22:03 UTC, a13x5 commented on docker/requirements.txt
No CR at the end of the file

2024-09-25 16:11 UTC, closed without merging

2024-09-25 17:33 UTC, PrashantR30 commented
Hi @a13x5 ,  I accidentally delete my fork, will re-issue a similar PR with the correction, soon.