Add airgap documentation
k0rdent/olddocs pull request #29
Opened 2024-10-31 18:26 UTC by squizzi

2024-11-05 01:48 UTC, slysunkin commented on docs/install/airgap.md
> +In order to install HMC in an airgapped environment, you need will need the
```suggestion
In order to install HMC in an air-gapped environment, you will need the
```

2024-11-05 01:48 UTC, slysunkin commented on docs/install/airgap.md
> +### Airgapped Installation
```suggestion
### Air-gapped Installation
```

2024-11-05 01:50 UTC, slysunkin commented on docs/install/airgap.md
> +### Airgapped Installation
On the other hand "airgapped" vs "air-gapped" vs "air gapped" is still a disputable topic.

2024-11-05 14:50 UTC, a13x5 requested changes
Mostly minor notes

2024-11-05 14:50 UTC, a13x5 commented on docs/install/airgap.md
> +  If you do not have a registry you can deploy a [local Docker registry](https://distribution.github.io/distribution/)
This will not work well with current implementation see [comment](https://github.com/Mirantis/hmc/pull/475#discussion_r1828502232)
NIT: IMO caveats of using the insecure registry should be noted briefly, but also it's a common knowledge, so it's for you to decide

2024-11-05 14:50 UTC, a13x5 commented on docs/install/airgap.md
> +  > [!NOTE]
Should be `> NOTE:`, since mkdocs has different markdown syntax. The one you're using is for Github

2024-11-05 14:50 UTC, a13x5 commented on docs/install/airgap.md
> +using both `docker login` and `helm registry login` before running the script.
Indentation is missing

2024-11-05 14:50 UTC, a13x5 commented on docs/install/airgap.md
> +  time all HMC charts MUST be hosted in a single chart repository.
Probably we should cover oci helm registry case (It works without changes in the scripts by adding `oci://` to the repo url)

2024-11-05 14:50 UTC, a13x5 commented on docs/install/airgap.md
> +  tar xvf hmc-airgap-<version>.tgz "images/hmc-images-<version>.tgz" -C /var/lib/k0s/images
I had issue with this command (the file didn't unpacked properly to `/var/lib/k0s/images`). Need to re-check

2024-11-07 19:23 UTC, Schnitzel requested changes

2024-11-07 19:23 UTC, Schnitzel commented on docs/install/airgap.md
> +tar xvf hmc-airgap-<version>.tgz scripts/airgap-push.sh
in my testing this doesn't work:

```
$ tar xvf hmc-airgap-0.0.3-50-ge85fe81.tgz scripts/airgap-push.sh
tar: scripts/airgap-push.sh: Not found in archive
```

when extracting the whole repo, I can see the file but it is not extracted, probably because it tries to be extracted a level higher and this is protected by tar

```
$ tar xvf hmc-airgap-0.0.3-50-ge85fe81.tgz -C airgap/
tar: Removing leading `../' from member names
tar: ../scripts/airgap-push.sh: Member name contains '..'
```

2024-11-07 19:32 UTC, Schnitzel commented on docs/install/airgap.md
> +tar xvf hmc-airgap-<version>.tgz scripts/airgap-push.sh
addressed myself in this commit: https://github.com/Mirantis/hmc/pull/475/commits/4fb4d54b153cc3f6c47b03761d10c5b19e2abecc

2024-11-07 22:11 UTC, squizzi commented on docs/install/airgap.md
> +tar xvf hmc-airgap-<version>.tgz scripts/airgap-push.sh
I accidentally force-pushed over this during a squash, but re-added it in https://github.com/Mirantis/hmc/pull/475/commits/a61f3d497d2d37fb9e531fad4d76a9b6e5f4c896

2024-11-11 23:57 UTC, a13x5 commented
@Schnitzel I rebased this branch, fixed markdown rendering issues and add the page to the nav. Please review it and approve again. Thanks

2024-11-18 16:51 UTC, Schnitzel commented
as 0.0.4 of 2A has just landed I'm going through this one last time and will merge

2024-11-19 02:35 UTC, Schnitzel approved these changes

2024-11-19 02:35 UTC, merged