Docs Cleanup for QuickStart and Credentials
k0rdent/olddocs pull request #31
Opened 2024-11-03 01:28 UTC by randybias

Standardized and streamlined quick start guides, glossaries, and setup instructions for Project 0x2A

**Details:**

- Enhanced README with standardized formatting for consistency.
- Updated glossary to include new terminology, reorganized definitions for clarity.
- Improved quick start guides for AWS, Azure, and vSphere:
  - Added consistent heading structure and note formats.
  - Introduced explicit template retrieval steps and validation checks.
  - Revised syntax for clarity in command examples and YAML configurations.
- Enhanced MkDocs configuration:
  - Added support for tables, admonition, and other markdown extensions.
  - Updated navigation structure for improved user experience.

2024-11-05 07:35 UTC, randybias reviewed
Looks good.... Let's see if this will auto-merge.

2024-11-05 15:05 UTC, Schnitzel requested changes

2024-11-05 15:05 UTC, Schnitzel commented on docs/quick-start/aws.md
> +  template: <Template Name> # The name of the template you want to use from above
I don't like this, this is a quick start which should bring the customer to a result with the least amount of decisions as possible. Trying to bring the concept of ClusterTemplates in here is too early. Yes we need a way to explain them how to use templates, how to find them, how to choose them, etc. But in this step of the customer journey I would not have them worry about templates yet.

2024-11-05 15:05 UTC, Schnitzel commented on docs/quick-start/aws.md
> +( kubectl -n hmc-system get secret my-aws-managedcluster1-kubeconfig -o jsonpath='{.data.value}' | base64 -d > my-aws-managedcluster1-kubeconfig.kubeconfig ) && KUBECONFIG="my-aws-managedcluster1-kub
I don't think this is needed a single oneliner. Having it in two lines explains the customer much better what is going on, and how they can run future `kubectl` commands themselves.

2024-11-05 15:17 UTC, a13x5 requested changes
Don't understand the introduction of admonitions in the quick start guides.
2A -> 0x2A rename probably should be discussed with @Schnitzel 

Rest looks good

2024-11-05 15:17 UTC, a13x5 commented on docs/quick-start/aws.md
> +    Skip steps below if you've already configured IAM policy for your AWS account
Is there a specific reason to switch to [admonitions](https://python-markdown.github.io/extensions/admonition/) from [markdown-callouts](https://oprypin.github.io/markdown-callouts/index.html)?

Most of the docs using latter, since it was introduced in #9. I don't see reason to use 2 different plugins with the same functionality, we should choose one.

2024-11-05 15:17 UTC, a13x5 commented on docs/quick-start/aws.md
> +( kubectl -n hmc-system get secret my-aws-managedcluster1-kubeconfig -o jsonpath='{.data.value}' | base64 -d > my-aws-managedcluster1-kubeconfig.kubeconfig ) && KUBECONFIG="my-aws-managedcluster1-kub
NIT:  Use of parenthesis isn't needed in this case and it's a bit unconventional outside of conditional statement.

2024-11-05 16:15 UTC, randybias commented on docs/quick-start/aws.md
> +    Skip steps below if you've already configured IAM policy for your AWS account
I went with the default in the Material theme.

2024-11-05 16:18 UTC, randybias commented on docs/quick-start/aws.md
> +  template: <Template Name> # The name of the template you want to use from above
This was one of the few places I stumbled in the documentation, since the version of the templates, for example, aren't always being updated in the documentation to match what is in a given release.  If we don't do this then every time we version the templates in a release we will have to manually update the quick starts to include any of the template version changes.

I found it more confusing that I didn't know how to figure out why my deployment didn't work than understanding the templates themselves.

2024-11-05 16:22 UTC, randybias commented on docs/quick-start/aws.md
> +( kubectl -n hmc-system get secret my-aws-managedcluster1-kubeconfig -o jsonpath='{.data.value}' | base64 -d > my-aws-managedcluster1-kubeconfig.kubeconfig ) && KUBECONFIG="my-aws-managedcluster1-kub
It makes sure everything in the sub shell exits cleanly in order to proceed.  If it's unconventional then I've been doing it unconventionally since the 1980s.  Regardless, due to Michael's other feedback this is split back into two commands so it's moot.

2024-11-05 16:31 UTC, randybias commented
> Don't understand the introduction of admonitions in the quick start guides. 2A -> 0x2A rename probably should be discussed with @Schnitzel
> 
> Rest looks good

For whatever it's worth, I was changing it everywhere.  Again, it was the default in the Material theme so I thought it made sense.  I agree that two different mechanisms for this doesn't make sense.  So after y'all make a decision I'll just go whichever way you decide.

If you decide to go with the admonitions, I will make certain it's done across all of the docs.

2024-11-05 17:07 UTC, a13x5 commented
>  So after y'all make a decision I'll just go whichever way you decide.
Got it! Let's keep using callouts and not admonitions then, since the syntax is better and it's less changes throughout the code (since we have callouts everywhere).

2024-11-06 02:20 UTC, Schnitzel commented on docs/quick-start/aws.md
> +  template: <Template Name> # The name of the template you want to use from above
>  If we don't do this then every time we version the templates in a release we will have to manually update the quick starts to include any of the template version changes.

yea, I'm ok with that, we have to update the docs anyway with every new 2A release. Rather spend some time updating docs and provide a super simple quickstart, than having confused first time users.
Also we can automate the updating of the docs.

2024-11-06 02:21 UTC, Schnitzel requested changes

2024-11-06 02:21 UTC, Schnitzel commented on docs/glossary.md
> +<<<<<<< HEAD
some merge conflict pieces

2024-11-06 02:43 UTC, randybias commented on docs/quick-start/aws.md
> +  template: <Template Name> # The name of the template you want to use from above
Alright.  I'll revert this.

2024-11-06 02:51 UTC, randybias commented on docs/quick-start/aws.md
> +  template: <Template Name> # The name of the template you want to use from above
Fixed.

2024-11-06 02:55 UTC, randybias commented on docs/glossary.md
> +<<<<<<< HEAD
fixed

2024-11-06 03:08 UTC, randybias commented on docs/glossary.md
> +<<<<<<< HEAD
Everything converted to callouts.

2024-11-06 03:09 UTC, randybias commented on docs/quick-start/aws.md
> +    Skip steps below if you've already configured IAM policy for your AWS account
Fixed.

2024-11-06 05:27 UTC, bnallapeta commented on docs/glossary.md
> +A Credential is a Kubernetes object that provides 2A with the necessary credentials to manage
This is sort of implying that credential is a generic kubernetes object. Its not. Better to rephrase this as:

Credential is a Custom Resource (CR) in HMC that supplies 2A with the necessary credentials to manage a specific infrastructure.

2024-11-06 05:31 UTC, bnallapeta commented on docs/glossary.md
> +### Provider (also Infrastructure Provider)
I think we should separate the two. 

Provider is a HMC specific concept where as InfrastructureProvider is a Cluster API CRD. 

InfrastructureProvider

InfrastructureProvider is a Kubernetes Custom Resource (CR) that defines the infrastructure-specific configuration needed for managing Kubernetes clusters. It enables Cluster API (CAPI) to provision and manage clusters on a specific infrastructure platform (e.g., AWS, Azure, VMware).

2024-11-06 05:32 UTC, bnallapeta commented on docs/index.md
> +In many ways "Project 2A and "HMC" are synonymous.
"Project 2A => "Project 2A"

2024-11-06 05:33 UTC, bnallapeta commented on docs/index.md
> + * **Hybrid Multi Cluster Management (HMC)**
in the main repo, HMC is expanded to just "Hybrid Multi Cluster" 

https://github.com/Mirantis/hmc?tab=readme-ov-file#mirantis-hybrid-multi-cluster-hmc-codename-project-0x2a

2024-11-06 05:35 UTC, bnallapeta commented on docs/index.md
> + * **Cluster State Management (SMC)**
Is this our own definition? If so, should it not be abbreviated to CSM? 🤔

2024-11-06 05:42 UTC, bnallapeta commented on docs/usage/cluster-update.md
> +kubectl patch managedcluster.hmc <Your Cluster Name> -n <Namespace> --patch '{"spec":{"template":"<new-template-name>"}}' --type=merge
standard convention in k8s to use lowercase without spaces.

<Your Cluster Name> => <your-cluster-name>
<Namespace> => <namespace>

2024-11-06 05:42 UTC, bnallapeta commented on docs/usage/cluster-update.md
> +kubectl get managedcluster.hmc <Your Cluster Name> -n <Namespace>
same as above

2024-11-06 05:43 UTC, bnallapeta commented on docs/usage/create-managed-cluster.md
> +      name: <Your Cluster Name>
same as above. please fix this in all places.

2024-11-06 05:45 UTC, bnallapeta reviewed
few comments to work on.

2024-11-06 09:18 UTC, randybias commented on docs/glossary.md
> +A Credential is a Kubernetes object that provides 2A with the necessary credentials to manage
Good catch.

2024-11-06 09:46 UTC, randybias commented on docs/glossary.md
> +### Provider (also Infrastructure Provider)
Changed provider to CAPI Provider and created new Infrastructure Provider entry.

2024-11-06 09:48 UTC, randybias commented on docs/index.md
> + * **Hybrid Multi Cluster Management (HMC)**
We are extremely inconsistent with our naming, acronyms, and more.  I really think we should fix that sooner as the problem just gets worse as we go along.  @Schnitzel @p5ntangle

2024-11-06 09:49 UTC, randybias commented on docs/index.md
> + * **Cluster State Management (SMC)**
I think we were trying to match HMC?  It's inconsistent for sure.  We have three acronyms or abbreviations that are all completely different.

2024-11-06 09:51 UTC, randybias commented on docs/usage/cluster-update.md
> +kubectl patch managedcluster.hmc <Your Cluster Name> -n <Namespace> --patch '{"spec":{"template":"<new-template-name>"}}' --type=merge
Can you show me this?  I find it harder to read because it looks like other text such as "hmc-system".  I think the variables to be interpolated should be clearly different in some manner.  All caps or something.  As it is every example command is lots of lower case and lots of '-'s and it makes it very challenging to read properly.  Italics.  Anything.  We just need a standard and I don't think lowercase is it. @Schnitzel @p5ntangle

2024-11-06 10:08 UTC, bnallapeta commented on docs/usage/cluster-update.md
> +kubectl patch managedcluster.hmc <Your Cluster Name> -n <Namespace> --patch '{"spec":{"template":"<new-template-name>"}}' --type=merge
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

This states that the resource names must conform to dns subdomain naming convention and thus the no capital letters, no spaces and other such rules. So, we end up following the same convention even for placeholders, but surrounded by <>

If you really want to distinguish that this is a placeholder for the user to fill, then I think its better to do all caps with underscore. 

```
<Your Cluster Name> => <YOUR_CLUSTER_NAME>
<Namespace> => <NAMESPACE>
```

2024-11-06 10:08 UTC, bnallapeta commented on docs/index.md
> + * **Cluster State Management (SMC)**
@p5ntangle ^^

2024-11-06 10:15 UTC, randybias commented on docs/usage/cluster-update.md
> +kubectl patch managedcluster.hmc <Your Cluster Name> -n <Namespace> --patch '{"spec":{"template":"<new-template-name>"}}' --type=merge
I see... I went through the Cluster API docs.  I still think it's horribly confusing, but I guess if we just want to conform rather than innovate we can do this.

2024-11-06 10:39 UTC, randybias commented on docs/usage/cluster-update.md
> +kubectl patch managedcluster.hmc <Your Cluster Name> -n <Namespace> --patch '{"spec":{"template":"<new-template-name>"}}' --type=merge
OK.  I found this:

https://kubernetes.io/docs/contribute/style/style-guide/

I'll follow that.  I've got to go back in and fix a bunch of things.  Standby.

2024-11-06 15:15 UTC, a13x5 commented on mkdocs.yml
> +  - admonition
We should remove it from here, since we decided to use `callouts`

2024-11-06 15:47 UTC, randybias commented on docs/usage/cluster-update.md
> +kubectl patch managedcluster.hmc <Your Cluster Name> -n <Namespace> --patch '{"spec":{"template":"<new-template-name>"}}' --type=merge
This is all fixed per the style guide.

2024-11-06 15:48 UTC, randybias commented on mkdocs.yml
> +  - admonition
Done.

2024-11-06 16:37 UTC, a13x5 approved these changes
LGTM

2024-11-07 02:04 UTC, Schnitzel commented on docs/index.md
> + * **Hybrid Multi Cluster (HMC) Management**
```suggestion
 * **Hybrid Multi-Cluster Controller (HMC)**
```

2024-11-07 02:04 UTC, Schnitzel commented on docs/index.md
> + * **Hybrid Multi Cluster (HMC) Management**
talked to @p5ntangle and we agreed on this naming

2024-11-07 02:05 UTC, Schnitzel commented on docs/index.md
> + * **Cluster State Management (SMC)**
```suggestion
 * **State Management Controller (SMC)**
```

2024-11-07 02:05 UTC, Schnitzel commented on docs/index.md
> + * **Cluster State Management (SMC)**
also verified this with @p5ntangle

2024-11-07 02:06 UTC, Schnitzel approved these changes

2024-11-07 02:07 UTC, merged