Add prerequisites & adjustment of quick start installation
k0rdent/olddocs pull request #38
Opened 2024-11-14 17:46 UTC by jlnhnng

2024-11-18 16:56 UTC, Schnitzel requested changes

2024-11-18 16:56 UTC, Schnitzel commented on docs/quick-start/prerequisites.md
> +
I'm not sure I'm a big fan of moving the requirements away from the Quickstart, this will require a first time user to go through 3 pages of documentation to have a cluster up and running (PreRequisites, General Quickstart and Infra specific Quickstart).
Could we leave the `Requirements` in the General Quickstart page, and reference to the additional prerequisites page?

2024-11-18 16:56 UTC, Schnitzel commented on docs/assets/architecture.png
can you provide the source of this? so we can update it whenever needed?

2024-12-06 13:45 UTC, jlnhnng commented on docs/quick-start/prerequisites.md
> +
Yes, sure. I can pull the latest and work your feedback in.

2024-12-06 13:47 UTC, jlnhnng commented on docs/assets/architecture.png
In which format would you like the diagram? I can export it EPS or SVG. I've created it via Sketch. So, can be a sketch document as well. 
Where is there best place to save the source?

2024-12-10 15:04 UTC, Schnitzel commented on docs/assets/architecture.png
> In which format would you like the diagram? I can export it EPS or SVG. I've created it via Sketch. So, can be a sketch document as well.
yea let's upload the sketch file, so we have something that can be actually edited if needed by other people.

>  Where is there best place to save the source? 

I would say also in the assets folder were the PNG lies

2024-12-11 09:43 UTC, jlnhnng commented on docs/assets/architecture.png
In which format would you like the diagram? Only PNG?

2025-01-06 08:23 UTC, randybias commented
There are going to be a large number of changes coming due to the repository move and the name change.  I suspect you will need to rebase this whole thing soon since it wasn't merged before now.  Just a headsup.

2025-01-09 02:22 UTC, randybias commented on docs/assets/architecture.png
I've talked to Nick, who owns the docs.  The source can be optional as he will likely re-work the diagrams across the docs in the near future.  So just the PNG for now will be fine.

2025-01-09 02:23 UTC, randybias commented
Just rebase and do another PR and then I think we can get this merged.  Turn around time will be faster from here on out.  Appreciate your patience.

2025-01-13 06:18 UTC, randybias commented
You need to rebase and resolve the conflicts.  In particular, 2a-installation.md -> installation.md.  Also, you made changes to mkdocs.yml that look like they need to be handled. @jlnhnng

2025-02-03 06:49 UTC, randybias commented
This was not rebased and now is woefully out of date.  I'm closing the PR.

2025-02-03 06:49 UTC, closed without merging