HMC-337: Updated docs + new  Navigation
k0rdent/olddocs pull request #7
Opened 2024-10-07 16:50 UTC by PrashantR30

This PR is the incremental development of Azure Docs resolving https://github.com/Mirantis/hmc/issues/337

2024-10-07 17:04 UTC, p5ntangle commented on .github/workflows/docs.yml
Please take the changes to workflows out of this PR, we dont need the branch to be included in the PR

2024-10-08 14:47 UTC, PrashantR30 commented on .github/workflows/docs.yml
The branch definition in .github/workflows/docs.yml was removed.

2024-10-14 17:34 UTC, a13x5 requested changes
Cluster identity section should be rewritten.
Several notes on style.

One major note here:
Please don't use extra long lines in markdown.  Use 75-80 columns rule, lines longer than that should be broke down. If there is no empty line between markdown will render it as a single line anyway (see other documents as a reference).

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/hosted-control-plane.md
> +> **Important:**: since Azure admission prohibits orphaned objects mutation you'll have to
Please use proper syntax for call-outs. See [markdown-callouts](https://oprypin.github.io/markdown-callouts/index.html) for more details.

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/main.md
> +# Installations methods
_Installation_ methods

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/main.md
> +- [Hosted Control Plane (Kosmotron) Guide](./hosted-control-plane.md)
_k0smotron_

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +## Register Resource Providers
Should be h3, since it's a part of prerequisites section

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +---
Why?

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +The service principal allows CAPZ to interact with the Azure API. To create one, run the following command, replacing <Subscription ID> with the ID retrieved in the previous step:
Previous item has indentation and this isn't. Please make sure that it's consistent

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +#### Create `AzureClusterIdentity`
The whole section should be rewritten to reflect new credentials changes

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +> **Important:** The root volume size cannot be smaller than the root volume size defined in your chosen VM image.
This ought to be a quick-start guide. I believe copying the whole cluster parameters section here missing the point. Just reference `cluster-parameters.md` in case user needs more detail.

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +By default, the latest official CAPZ Ubuntu-based image is used unless otherwise specified.
Again since we have default, you can omit this section.

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +> **Important:** The root volume size cannot be smaller than the root volume size defined in your chosen VM image.
Proper call-outs

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +> **Important:** Save these credentials securely, as they will be used to create the `AzureClusterIdentity` and its secret, and should be treated like passwords.
Proper call-outs

2024-10-14 17:34 UTC, a13x5 commented on docs/azure/quick-start.md
> +> **Note:** In this setup, all control plane components for managed clusters will reside within the management cluster, offering centralized control and easier management.
Proper call-outs

2024-10-18 16:30 UTC, PrashantR30 commented on docs/azure/quick-start.md
> +---
Removed

2024-10-18 16:31 UTC, PrashantR30 commented on docs/azure/quick-start.md
> +#### Create `AzureClusterIdentity`
The text were replaced from the newly submitted credentials changes.

2024-10-18 16:32 UTC, PrashantR30 commented on docs/azure/quick-start.md
> +> **Important:** The root volume size cannot be smaller than the root volume size defined in your chosen VM image.
Yes, this section was removed and replaced by a link to the cluster machine parameters page.

2024-10-18 16:33 UTC, PrashantR30 commented on docs/azure/quick-start.md
> +By default, the latest official CAPZ Ubuntu-based image is used unless otherwise specified.
I remove this section from the Quick Start page, but left it in the machine-parameters page.

2024-10-18 16:35 UTC, PrashantR30 commented
Hello @a13x5 , please review as the recommendation were applied including code changes and 75-80 columns was applied.

2024-10-18 16:52 UTC, PrashantR30 commented
Preview of the page is: https://prashantr30.github.io/project-2a-docs-2/azure/quick-start/

2024-10-18 18:10 UTC, a13x5 requested changes
Formatting looks better, but the the guide is impossible to finish successfully

2024-10-18 18:10 UTC, a13x5 commented on docs/azure/quick-start.md
> +### Register resource providers
This section should mention the [official documentation guide](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types)

2024-10-18 18:10 UTC, a13x5 commented on docs/azure/quick-start.md
> +> reside within the management cluster, offering centralized control and easier management.
I don't see the need for this in a separate section

2024-10-18 18:10 UTC, a13x5 commented on docs/azure/quick-start.md
This guide is lacking several things:
- Clear outline, i.e. the summary of steps that should be done and what user should expect
- Actual steps where we're creating the cluster

Currently if I will follow this guide I will install `kubectl`, `az` and (probably) will create the credentials and several yaml files. 
Where should I apply them? Where should I configure my cluster? I only know that `Credential` object I created should be referenced in some `ManagedCluster` object. 

Please rewrite.

2024-10-18 18:10 UTC, a13x5 commented on docs/azure/main.md
> -hosted control plane cluster on Azure.
I'm against deleting it, just make separate section like `Parameter reference` or `Additional resources`

2024-10-31 03:15 UTC, Schnitzel commented
these changes have been incorporated as part of https://github.com/Mirantis/project-2a-docs/pull/25

2024-10-31 03:15 UTC, closed without merging